name: Build and Deploy to K8s

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend_ai_realtime_pong:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend_ai_realtime_pong:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to K8s
        run: |
          kubectl set image deployment/backend-deployment backend=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend_ai_realtime_pong:latest -n ai_realtime_pong_prod
          kubectl set image deployment/frontend-deployment frontend=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend_ai_realtime_pong:latest -n ai_realtime_pong_prod
          kubectl apply -f k8s/